version: '3.9'

x-app-base: &app_base
  build: .
  environment: &app_environment
    APP_HOST: localhost
    ASSET_HOST: null
    FORCE_SSL: 'false'
    SECRET_KEY_BASE: something-long-and-secret
    HONEYBADGER_API_KEY: null
    PLAUSIBLE_URL: null
    LOCKUP_CODEWORD: null

services:
  app:
    <<: *app_base
    environment:
      <<: *app_environment
    ports:
      - 3000
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 3000 || exit 1']
    networks:
      - public
      - internal

networks:
  public:
    external: true
  internal:
    driver_opts:
      encrypted: ''
